version: "3"
services:

  app_container:
    command: npm run server
    build:
      context: .
    restart: on-failure
    env_file: .env

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 12380:80
    depends_on:
      - app_container
